// Generated by specs/retinal-vision/assets/03/export-eye-rig.mjs; do not edit.
// Neutral asset centres and reference optical axes; apply the full native body pose.
export const retinalEyeRig = Object.freeze({
  rigSha256: "95d00abd9162e75517f70ba9cc6764336b1f07dd0bf83e6fc75179c0435d667f",
  assetSha256: "2c7a3398c2b0f9fdae6f62351379b4ea5a01d7fcf6f3a1d582d4c5106ab75b57",
  referenceProfileSha256: "9e9ff3e3e80cc85b7c8afb4679d849e2b90388089a79878bddff5c77b1ded771",
  units: "metres",
  bodyFrame: "+Z forward, +Y up; physical left is +X",
  eyes: Object.freeze([Object.freeze({
  side: "L",
  sourceMesh: "EyeR021",
  positionMetres: Object.freeze([0.0003575129885489114, 0.0013760818013758619, 0.0009108809958464541] as const),
  cameraToBodyQuaternion: Object.freeze([-0.00020825005507139657, -0.8523162720044343, -0.0003393611604951547, 0.5230265900911543] as const),
}), Object.freeze({
  side: "R",
  sourceMesh: "EyeL021",
  positionMetres: Object.freeze([-0.00035751298854891725, 0.0013760818013758456, 0.0009108809958464577] as const),
  cameraToBodyQuaternion: Object.freeze([-0.00047047222434785425, 0.8523158359269963, -0.000755861097007767, 0.5230266944984298] as const),
})] as const),
});
