import type { ToolKind } from "../../packages/sim-client/src";
import banana from "../food/banana/banana.glb?url";
import fruit from "../food/apple/apple.glb?url";
import crumbs from "../food/crumbs.glb?url";
import vinegar from "../household/vinegar/vinegar.glb?url";
import fan from "../household/fan/fan.glb?url";
import lamp from "./lamp.glb?url";
import shade from "./shade.glb?url";
import wornShoes from "../household/worn-shoes/worn-shoes.glb?url";
import dirtyDishes from "../household/dirty-dishes/dirty-dishes.glb?url";
import laundry from "../household/crumpled-laundry/crumpled-laundry.glb?url";
import bugZapper from "../household/bug-zapper/bug-zapper.glb?url";
import sleepingCat from "../household/sleeping-cat/sleeping-cat.glb?url";
export const placementAssetUrls = { fruit, banana, crumbs, vinegar, fan, lamp, shade, wornShoes, dirtyDishes, laundry, sleepingCat, bugZapper } as const satisfies Record<ToolKind, string>;
