import { cp, mkdir, readFile } from 'node:fs/promises';
const source = new URL('../data/processed/brain/', import.meta.url);
const destination = new URL('../apps/web/public/brain/', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('manifest.json', source), 'utf8'));
const binary = await readFile(new URL('graph.bin', source));
const hash = new Bun.CryptoHasher('sha256').update(binary).digest('hex');
if (manifest.synthetic || manifest.graphHash !== hash) throw new Error('Prepare and verify the real graph before building.');
await mkdir(destination, { recursive: true });
for (const file of ['graph.bin', 'manifest.json']) await cp(new URL(file, source), new URL(file, destination));
console.log(`Prepared ${manifest.neuronCount.toLocaleString()} real neurons for static browser loading.`);
